services:
  postgres:
    image: postgres:16
    container_name: survey_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - survey_postgres_data:/var/lib/postgresql/data

volumes:
  survey_postgres_data: